FROM node:20

RUN mkdir /workspace
WORKDIR /workspace

RUN apt-get update && apt-get install -y --no-install-recommends \
	git \
	&& rm -rf /var/lib/apt/lists/*

RUN npm i -g pnpm

COPY . .

# RUN pnpm install

EXPOSE 3000
