FROM node:20

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN mkdir /workspace
WORKDIR /workspace
COPY . .

RUN apt-get update && apt-get install -y --no-install-recommends \
	git \
	&& rm -rf /var/lib/apt/lists/*

RUN npm i -g pnpm

RUN pnpm install

EXPOSE 5173

CMD ["pnpm", "dev", "--host"]
