version: "3.9"
services:
  storybook:
    build:
      context: .
      dockerfile: Dockerfile.local
      network: host
    ports:
      - "5173:5173"
    volumes:
      - .:/workspace
    tty: true
